# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: blog.proto for package 'blog'

require 'grpc'
require './lib/protos/blog_pb'

module Blog
  module BlogService
    # The greeting service definition.
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'blog.blog_service'

      rpc :Show, ShowRequest, ShowReply
    end

    Stub = Service.rpc_stub_class
  end
end
