# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blog.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("blog.proto", :syntax => :proto3) do
    add_message "blog_app.Blog" do
      optional :id, :int32, 1
      optional :title, :string, 2
    end
    add_message "blog_app.ShowRequest" do
      optional :id, :int32, 1
    end
    add_message "blog_app.ShowReply" do
      optional :blog, :message, 1, "blog_app.Blog"
    end
  end
end

module BlogApp
  Blog = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blog_app.Blog").msgclass
  ShowRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blog_app.ShowRequest").msgclass
  ShowReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blog_app.ShowReply").msgclass
end
