# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: blog.proto for package 'blog_app'

require 'grpc'
require 'blog_pb'

module BlogApp
  module BlogPost
    # The greeting service definition.
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'blog_app.blog_post'

      rpc :Show, ShowRequest, ShowReply
    end

    Stub = Service.rpc_stub_class
  end
end
